name: Deploy to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Récupère le code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Se connecte à Docker Hub avec les secrets configurés
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PWD }}

      # 3. Construit l'image et la pousse vers Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Remplacez ci-dessous 'votre-pseudo' par votre vrai nom d'utilisateur Docker Hub
          # Exemple : jean/lab5-cicd:latest
          tags: ${{ secrets.DOCKER_LOGIN }}/lab5-cicd:latest